---
addusers:
  rke:
    name: rke
    comment: "RKE user"
    createhome: yes
    system: yes
    shell: /bin/bash

adduser:
  name: "{{ user.name }}"
  group: "{{ user.name|default(None) }}"
  comment: "{{ user.comment|default(None) }}"
  shell: "{{ user.shell|default(None) }}"
  system: "{{ user.system|default(None) }}"
  createhome: "{{ user.createhome|default(None) }}"

