fullnameOverride: ingress-nginx
controller:
  kind: DaemonSet
  hostNetwork: true
  hostPort:
    enabled: true
  service:
    enabled: false
  publishService:
    enabled: false
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  config:
    use-forwarded-headers: "true"
